name: QuAcK Compilation

on:
  push:
    branches:
    - ci
  pull_request:
    branches:
    - master


jobs:

  configuration:
    runs-on: ubuntu-20.04
    name: Dependencies

    steps:
       - name: install dependencies
         run: |
           sudo apt install gfortran gcc liblapack-dev libblas-dev wget python3 make m4 pkg-config

  compilation:
    name: Compilation
    runs-on: ubuntu-20.04

    steps:
       - uses: actions/checkout@v3
       - name: Configuration
         run: |
              ./configure -i ninja || :
       - name: Compilation
         run: |
              bash -c "source quack.rc ; cd src ; exec make"



