name: QuAcK Configuration

on:
  push:
    branches:
    - ci
  pull_request:
    branches:
    - master
  schedule:
  - cron: "00 20 * * 6"


jobs:

  configuration:
    runs-on: ubuntu-20.04
    name: Dependencies

    steps:
       - uses: actions/checkout@v3
       - name: Install dependencies
         run: |
           sudo apt install gfortran gcc liblapack-dev libblas-dev wget python3 make m4 pkg-config libhdf5-dev
       - name: ninja
         run: |
              ./configure -i ninja || echo "Configuration failed"
