name: QuAcK Testing


on:
  workflow_run:
    workflows: ["QuAcK Compilation"]
    types:
      - completed


jobs:

  test:
    runs-on: ubuntu-20.04
    name: Run Tests

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download compiled binary from previous workflow
      uses: actions/download-artifact@v3
      with:
        name: fortran-binary
        path: ./bin/QuAcK

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyscf

    - name: Run tests
      run: |
        bash -c "source quack.rc ; cd tests ; python lunch_bench.py -s light -t 1e-1"
